return {
    "felipeagc/fleet-theme-nvim",
    "sainnhe/sonokai",
    "eldritch-theme/eldritch.nvim",
    "diegoulloao/neofusion.nvim",
    "loctvl842/monokai-pro.nvim",
    "rebelot/kanagawa.nvim",
    "ellisonleao/gruvbox.nvim",
    "luisiacc/gruvbox-baby",
    "nuvic/flexoki-nvim",
    "Mofiqul/vscode.nvim",
    "andreasvc/vim-256noir",
    "sainnhe/sonokai",
    "junegunn/seoul256.vim",
    "AlexvZyl/nordic.nvim",
    "shaunsingh/nord.nvim",
    "maxmx03/solarized.nvim",
    "nyoom-engineering/oxocarbon.nvim",
    "datsfilipe/min-theme.nvim",
    "ribru17/bamboo.nvim",
    "slugbyte/lackluster.nvim",
    { "embark-theme/vim", name = "embark" },
    {
        "Biscuit-Theme/nvim",
        name = "biscuit",
    },
    {
        "rose-pine/neovim",
        name = "rose-pine",
    },
    {
        "zenbones-theme/zenbones.nvim",
        dependencies = "rktjmp/lush.nvim",
    },
}
