local header = {
    { "En el nombre del Padre, y del Hijo, Espíritu Santo.", "", "Amén." },
    { "In the name of the Father, and of the Son, and of the Holy Spirit.", "", "Amen." },
    {
        "I believe in God, the Father almighty, Creator of Heaven and earth.",
        "And in Jesus Christ, His only Son, our Lord, Who was conceived by",
        "the Holy Spirit, born of the Virgin Mary, suffered under Pontius",
        "Pilate was crucified, died, and was buried. He descended into Hell.",
        "The third day He rose again from the dead. He ascended into Heaven,",
        "and sits at the right hand of God, the Father almighty. He shall come",
        "again to judge the living and the dead. I believe in the Holy Spirit,",
        "the holy Catholic Church, the communion of saints, the forgiveness of",
        "sins, the resurrection of the body, and life everlasting.",
        "",
        "Amen.",
    },
    {
        "Creo en Dios, Padre todopoderoso, creador del Cielo y de la Tierra.",
        "Creo en Jesucristo su único Hijo, Señor Nuestro, que fue concebido",
        "por obra y gracia del Espíritu Santo; nació de Santa María Virgen;",
        "padeció bajo el poder de Poncio Pilato; fue crucificado, muerto y",
        "sepultado; descendió a los infiernos; al tercer día resucitó de",
        "entre los muertos; subió a los cielos y está sentado a la derecha de",
        "Dios Padre; desde allí ha de venir a juzgar a vivos y muertos. Creo en",
        "el Espíritu Santo, la Santa Iglesia Católica, la comunión de los Santos",
        "el perdón de los pecados la resurrección de la carne y la vida eterna.",
        "",
        "Amén.",
    },
    {
        "Our Father, Who art in Heaven, hallowed be Thy Name.",
        "Thy kingdom come, Thy will be done on earth as it is in",
        "Heaven. Give us this day our daily bread, and forgive us",
        "our trespasses, as we forgive those who trespass against us.",
        "And lead us not into temptation, but deliver us from evil.",
        "",
        "Amen.",
    },
    {
        "Padre nuestro, que estás en el cielo.",
        "Santificado sea tu nombre. Venga tu reino.",
        "Hágase tu voluntad en la tierra como en el cielo.",
        "Danos hoy nuestro pan de cada día. Perdona",
        "nuestras ofensas, como también nosotros",
        "perdonamos a los que nos ofenden. No nos dejes",
        "caer en tentación y líbranos del mal.",
        "",
        "Amén.",
    },
    {
        "Hail Mary full of grace, the Lord is",
        "with thee. Blessed art thou among women,",
        "and blessed is the fruit of thy womb, Jesus.",
        "Holy Mary, Mother of God, pray for us",
        "sinners, now and at the hour of our death.",
        "",
        "Amen.",
    },
    {
        "Dios te salve, María. Llena eres de gracia: El",
        "Señor es contigo. Bendita eres entre todas las",
        "mujeres. Y bendito es el fruto de tu vientre:",
        "Jesús. Santa María, Madre de Dios, ruega por",
        "nosotros pecadores, ahora y en la hora de nuestra",
        "muerte.",
        "",
        "Amén.",
    },
    {
        "Oh Jesús mío, perdóna nuestros pecados,",
        "líbranos del fuego del infierno, lleva a todas las",
        "almas al cielo, especialmente a las más",
        "necesitadas de tu misericordia.",
        "",
        "Amén.",
    },
    {
        "O my Jesus, forgive us our sins, save us",
        "from the fires of Hell; lead all souls to",
        "Heaven, especially those in most need of",
        "Thy mercy.",
        "",
        "Amen.",
    },
    {
        "Gloria al Padre, y al Hijo, y al Espíritu Santo;",
        "Como era en el principio, ahora, y siempre, por",
        "los siglos de los siglos.",
        "",
        "Amén.",
    },
    {
        "Glory be to the Father, and to the Son, and to the",
        "Holy Spirit. As it was in the beginning, is now,",
        "and shall ever be, world without end.",
        "",
        "Amen.",
    },
    {
        "Hail holy queen, mother of mercy;",
        "our life, our sweetness, and our hope. To",
        "thee do we cry, poor banished children of",
        "Eve. To thee do we send up our sighs,",
        "mourning and weeping in this vale of tears.",
        "Turn, then, most gracious advocate, thine",
        "eyes of mercy toward us. And after this, our",
        "exile, show unto us the blessed fruit of thy",
        "womb, Jesus. O clement, O loving, O sweet",
        "Virgin Mary. Pray for us, O holy Mother of",
        "God, that we may be made worthy of the",
        "promises of Christ.",
        "",
        "Amen.",
    },
    {
        "Dios te salve, Reina y Madre, madre de",
        "misericordia, vida, dulzura y esperanza nuestra,",
        "Dios te salve. A ti llamamos los desterrados hijos",
        "de Eva. A ti suspiramos gimiendo y llorando en",
        "este valle de lágrimas. Ea, pues, Señora, abogada",
        "nuestra: vuelve a nosotros esos tus ojos",
        "misericordiosos. Y después de este destierro,",
        "muéstranos a Jesús, fruto bendito de tu vientre.",
        "Oh clemente, oh piadosa, oh dulce Virgen María.",
        "Ruega por nosotros, Santa Madre de Dios, para",
        "que seamos dignos de alcanzar las promesas de",
        "nuestro Señor Jesucristo.",
        "",
        "Amén",
    },
    {
        "O God, whose only-begotten Son by",
        "His life, death and resurrection, has",
        "purchased for us the rewards of eternal life;",
        "grant, we beseech Thee, that by meditating",
        "upon these mysteries of the Most Holy",
        "Rosary of the Blessed Virgin Mary, we may",
        "imitate what they contain and obtain what",
        "they promise, through the same Christ our",
        "Lord.",
        "",
        "Amen.",
    },
    {
        "Oh Dios cuyo unigénito hijo con su vida,",
        "muerte y resurrección nos alcanzó el premio de",
        "la vida eterna, concédenos a los que recordamos",
        "estos misterios del Santo Rosario, imitar lo que",
        "contienen y alcanzar lo que prometen, por el",
        "mismo Jesucristo Nuestro Señor.",
        "",
        "Amén.",
    },
}

local header_formatted = table.concat(header[math.random(#header)], "\n")

return {
    "folke/snacks.nvim",
    lazy = false,
    opts = {
        bigfile = {
            enable = true,
            notify = true,
            size = 1 * 1024 * 1024,
            setup = function(ctx)
                if vim.fn.exists ":NoMatchParen" ~= 0 then
                    vim.cmd [[NoMatchParen]]
                end
                Snacks.util.wo(0, { foldmethod = "manual", statuscolumn = "", conceallevel = 0 })
                vim.b.minianimate_disable = true
                vim.schedule(function()
                    if vim.api.nvim_buf_is_valid(ctx.buf) then
                        vim.bo[ctx.buf].syntax = ctx.ft
                    end
                end)
            end,
        },
        indent = {
            enable = true,
            animate = {
                enabled = false,
            },
        },
        dashboard = {
            enabled = true,
            width = 60,
            row = nil,
            col = nil,
            pane_gap = 4,
            autokeys = "1234567890abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ",
            preset = {
                header = header_formatted,
                pick = nil,
                keys = {
                    {
                        icon = "󰖌",
                        key = "e",
                        desc = "Open Oil",
                        action = ":Oil",
                    },
                    {
                        icon = "󰱼",
                        key = "f",
                        desc = "Find File",
                        action = ":lua Snacks.dashboard.pick('files')",
                    },
                    {
                        icon = " ",
                        key = "g",
                        desc = "Find Text",
                        action = ":lua Snacks.dashboard.pick('live_grep')",
                    },
                    {
                        icon = " ",
                        key = "r",
                        desc = "Recent Files",
                        action = ":lua Snacks.dashboard.pick('oldfiles')",
                    },
                    {
                        icon = " ",
                        key = "t",
                        desc = "Theme Chooser",
                        action = ":Telescope colorscheme_chooser",
                    },
                    {
                        icon = "󰒲 ",
                        key = "L",
                        desc = "Lazy",
                        action = ":Lazy",
                        enabled = package.loaded.lazy ~= nil,
                    },
                    { icon = " ", key = "q", desc = "Quit", action = ":qa" },
                },
            },
        },
    },
}
